// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Inject Vercel Supabase integration variables as fallbacks
if (!process.env["DATABASE_URL"] && process.env["POSTGRES_PRISMA_URL"]) {
  process.env["DATABASE_URL"] = process.env["POSTGRES_PRISMA_URL"];
}
if (!process.env["DIRECT_URL"] && process.env["POSTGRES_URL_NON_POOLING"]) {
  process.env["DIRECT_URL"] = process.env["POSTGRES_URL_NON_POOLING"];
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // @ts-ignore - directUrl exists in Prisma 7 config but is missing in the TypeScript types of some versions
    directUrl: process.env["DIRECT_URL"],
  },
});
