// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Inject Vercel Supabase integration variables as fallbacks
if (!process.env["DATABASE_URL"]) {
  process.env["DATABASE_URL"] = process.env["POSTGRES_PRISMA_URL"] || process.env["DATABASE_POSTGRES_PRISMA_URL"];
}

// Automatically generate DIRECT_URL for migrations if using Supabase pooler on port 6543
if (process.env["DATABASE_URL"] && process.env["DATABASE_URL"].includes(":6543")) {
  process.env["DIRECT_URL"] = process.env["DATABASE_URL"].replace(":6543", ":5432");
} else if (!process.env["DIRECT_URL"]) {
  process.env["DIRECT_URL"] = process.env["POSTGRES_URL_NON_POOLING"] || process.env["DATABASE_POSTGRES_URL_NON_POOLING"];
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
